name: "Deploy to EC2 Instance"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build Docker Image"
        run: |
          docker login -u yukeshdhakal -p $DOCKERHUB_PAT
          docker build -t yukeshdhakal/devopscw .
          docker push yukeshdhakal/devopscw
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

      - name: "Configure SSH"
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      
      - name: "Setup SSH Key for Server Access"
        run: |
          echo "$SSH_KEY64" | base64 -d > ssh_key.pem
          chmod 400 ssh_key.pem
          ls -la ssh_key.pem  # To verify file size and permissions
        env: 
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      # - name: "Test SSH Connection"
      #   run: ssh -v ubuntu@$SERVER_IP -i ssh_key.pem 'echo "Connection successful"'

      - name: "Docker Pull and Restart Docker"
        run: |
          ssh ubuntu@$SERVER_IP -i ssh_key.pem 'docker pull yukeshdhakal/devopscw'
          ssh ubuntu@$SERVER_IP -i ssh_key.pem 'docker stop yukesh-front || true'
          ssh ubuntu@$SERVER_IP -i ssh_key.pem 'docker rm yukesh-front || true'
          ssh ubuntu@$SERVER_IP -i ssh_key.pem 'docker run --name yukesh-front -p 80:80 -d yukeshdhakal/devopscw'