name: "Deploy to Server"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build and Push Docker Image"
        run: |
          docker login -u yukeshdhakal -p $DOCKERHUB_PAT
          docker build -t yukeshdhakal/devopscw .
          docker push yukeshdhakal/devopscw
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

      - name: "Setup SSH"
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: "Decode and Save SSH Key"
        run: |
          echo "$SSH_KEY64" | base64 -d > pem.pem
          chmod 400 pem.pem
          ssh-keygen -R $SERVER_IP
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      - name: "Deploy to EC2"
        run: |
          ssh -i pem.pem ubuntu@$SERVER_IP << 'EOF'
          docker pull yukeshdhakal/devopscw
          docker stop yukesh-front || true
          docker rm yukesh-front || true
          docker run --name yukesh-front -p 80:80 -d yukeshdhakal/devopscw
          EOF
